version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: evently
      POSTGRES_USER: api-user
      POSTGRES_PASSWORD: password123
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  my_dbdata:
